### PR TITLE
Patch for: ZBXNEXT-2315

### PR DESCRIPTION
**Pull request by anttiviljami**
Ticket link: https://support.zabbix.com/browse/ZBXNEXT-2315

### CODE REVIEW

**Comment by richlv** [comment]
thank you - the patch is simple, but could you please also add the "patches.def" entry ? see the other entries for examples, and if it's unclear, please do ask on IRC :)

**Comment by anttiviljami** [comment]
Will that do? :)

**Comment by anttiviljami** [comment]
Where's the irc for the Zabbix community btw? :)

**Comment by richlv** [comment]
thank you - I'd have to dig in a bit more, as this isn't just a frontend patch (the 'f' flag). will try to check it soon.
regarding IRC, it's #zabbix on freenode - see http://zabbix.org/wiki/Getting_help#IRC for more detail

**Comment by richlv** [comment]
merging as-is, will change the patch type afterwards.
thank you, Antti :)

**Pull request merged**
